name: petadoptprueba2b
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ============ ENTORNO DE VARIABLES ============
  flutter_dotenv: ^5.1.0

  # ============ BACKEND ============
  supabase_flutter: ^2.8.0

  # ============ UI & FONTS ============
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1

  # ============ IMÃGENES ============
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

  # ============ MAPAS & GPS ============
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

  # ============ IA GEMINI ============
  google_generative_ai: ^0.4.6

  # ============ UTILIDADES ============
  intl: ^0.19.0
  uuid: ^4.5.1

  # ============ OAUTH GOOGLE ============
  google_sign_in: ^6.2.2

  # ============ NOTIFICACIONES PUSH ============
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
